Fix: www pool variables
geerlingguy/ansible-role-php pull request #326
Opened 2021-03-25 21:12 UTC by wells

- Update www.conf template to use all current variables
- Update configure-fpm task to overwrite www.conf with template every time
- Add `php_fpm_pm` and `php_fpm_pm_max_requests` variables for template

2021-04-23 12:06 UTC, shakalandy commented
Please have a look here @geerlingguy as it enhances features regarding PHP 8.x - thanks!

2021-04-23 14:39 UTC, geerlingguy requested changes

2021-04-23 14:39 UTC, geerlingguy commented on templates/www.conf.j2
> +pm = {{ php_fpm_pm }}
I think we should limit this PR's scope. #302 already looks at rearranging the way pools work. This PR should focus on just the JIT variables, IMO.

2021-05-06 17:17 UTC, geerlingguy commented
After merging #302 this PR is a bit messy — if there are still other changes can you consider submitting a new one?

2021-05-06 17:17 UTC, closed without merging